
<?php
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "loade";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}

$sql = '';
$sql .= "INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES
    ('GOSURF10','Globe','40MB internet data','1 day','10'),
    ('GOSURF15','Globe','100MB of mobile internet data+ 30MB for Instragram','2 days','15'),
    ('GOSURF30','Globe','300MB of mobile internet data+ 50MB for Facebook, Instagram, Viber or SnapChat','2 days','30'),
    ('GOSURF50','Globe','2GB of mobile internet data+ 1GB for GoWATCH & PLAY, GoSHARE & SHOP, GoLISTEN & TRAVEL, or GoLEARN & WORK+ Unlimited texts to all networks','3 days','50'),
    ('GOSURF99','Globe','200MB of mobile internet data+ 1GB for app of choice','30 days','99'),
    ('GOSURF199','Globe','500MB of mobile internet data+ 1GB for app of choice','30 days','199'),
    ('GOSURF299','Globe','2GB of mobile internet data+ 10GB for GoWATCH & PLAY, GoSHARE & SHOP, GoLISTEN & TRAVEL, or GoLEARN & WORK','30 days','299'),
    ('GOSURF499','Globe','3GB of mobile internet data+ 1GB for app of choice','30 days','499'),
    ('GOSURF599','Globe','5GB of mobile internet data+ 10GB for GoWATCH & PLAY, GoSHARE & SHOP, GoLISTEN & TRAVEL, or GoLEARN & WORK','30 days','599'),
    ('GOSURF999','Globe','10GB of mobile internet data+ 10GB for app bundle','30 days','999'),
    ('GOSURF1299','Globe','15GB of mobile internet data+ 10GB for app bundle','30 days','1299'),
    ('UNLI10','Globe','Unlimited calls and texts to Globe or TM','1 day','10'),
    ('SULITXT15','Globe','100 texts to Globe or TM','1 day','15'),
    ('GOUNLI20','Globe','Unlimited calls to Globe or TM+ Unlimited texts to all networks+ 20MB internet data','1 day','20'),
    ('GOUNLI25','Globe','Unlimited calls to Globe or TM+ Unlimited texts to all networks+ FREE Unlimited Viber','1 day','25'),
    ('GOUNLI30','Globe','Unlimited calls to Globe or TM+ Unlimited texts to all networks+ 30MB internet data','2 day','30'),
    ('GOUNLI50','Globe','Unlimited calls to Globe or TM+ Unlimited texts to all networks+ 50 MB mobile internet','3 days','50'),
    ('GOUNLI95','Globe','Unlimited calls to Globe and TM+ Unlimited texts to all networks+ 100MB internet data','7 days','95'),
    ('GOUNLI180','Globe','Unlimited calls to Globe and TM+ Unlimited texts to all networks+ 150MB internet data','15 days','180'),
    ('GOUNLI350','Globe','Unlimited calls to Globe and TM+ Unlimited texts to all networks+ 200MB internet data','30 days','350'),
    ('Tawag 236','Globe','20 minutes calls to Globe or TM for ₱20','20 minutes','20'),
    ('ATXT20','Globe','250 texts to all networks','1 day','20'),
    ('UNLITXT20','Globe','Unlimited texts to Globe or TM','1 day','20'),
    ('UNLITXT40','Globe','Unlimited texts to Globe or TM','2 days','40'),
    ('GOUNLITXT49','Globe','Unlimited texts to Globe or TM','7 days','49'),
    ('UNLITXT80','Globe','Unlimited texts to Globe or TM','5 days','80'),
    ('ATXTPLUS20','Globe','10 minutes calls to Globe or TM+ 250 texts to all networks','1 day','20'),
    ('Games 15','Globe','100MB for games (see Game Bundle Apps below)','1 day','15'),
    ('Games 20','Globe','100MB for games (see Game Bundle Apps below)','2 days','20'),
    ('Games 50','Globe','300MB for games (see Game Bundle Apps below)','7 days','50'),
    ('Games 99','Globe','300MB for games (see Game Bundle Apps below)','30 days','99'),
    ('UALLPLUS25','Globe','Unlimited calls to Globe and TM+ Unlimited texts to Globe and TM+ 1 hour mobile internet','1 day','25'),
    ('GOALLNET25','Globe','Unlimited texts to Globe or TM+ 75 minutes calls to Globe or TM+ 5 MB for Facebook','1 day','25'),
    ('GOALLNET30','Globe','Unlimited calls and texts to all networks+ 100MB mobile data','1 day','30'),
    ('GOALLNET50','Globe','Unlimited calls and texts to all networks+ 300MB mobile data','3 days','50'),
    ('GOALLNET70','Globe','Unlimited texts to Globe or TM+ 115 minutes calls to Globe or TM+ 5MB for Facebook','3 days','70'),
    ('GOALLNET200','Globe','Unlimited texts to Globe or TM+ 410 minutes calls to Globe or TM+ 10 MB for Facebook','7 days','200'),
    ('GOALLNET300','Globe','Unlimited texts to Globe or TM+ 580 minutes calls to Globe or TM+ 10MB for Facebook','15 days','300'),
    ('GOALLNET500','Globe','Unlimited texts to Globe or TM+ 710 minutes calls to Globe or TM+ 10 MB for Facebook',' 30 days','500'),
    ('GOTSCOMBOKEA37','Globe','1GB of mobile internet data+ 20 texts to all networks','1 day','37'),
    ('GO19','Globe','Unlimited texts to all networks+ 20 minutes calls to Globe or TM+ 15MB internet data','1 day','19'),
    ('Go50','Globe','5GB data+ Unlimited texts to all networks','3 days','50'),
    ('Go90','Globe','8GB data+ Unlimited texts to all networks','7 days','90'),
    ('Go120','Globe','10GB data+ Unlimited texts to all networks+ Unlimited calls to Globe or TM','7 days','120'),
    ('Go140','Globe','11GB data+ Unlimited texts to all networks+ Unlimited calls to Globe or TM','7 days','140'),
    ('GOSAKTO70/GOTSCOMBODD70','Globe','1GB of mobile internet data+ Unlimited texts to all networks+ 1GB per day for GoWATCH&PLAY and GoSHARE&SHOP','7 days','70'),
    ('GOSAKTO90/GOTSCOMBODD90','Globe','2GB of mobile internet data+ Unlimited texts to all networks+ 1GB per day for GoWATCH&PLAY and GoSHARE&SHOP','7 days','90'),
    ('GOSAKTO120','Globe','3GB of mobile internet data+ Unlimited calls to Globe or TM+ Unlimited texts to all networks+ 1GB per day for GoWATCH&PLAY and GoSHARE&SHOP','7 days','120'),
    ('GoSAKTO140','Globe','4GB data+ Unlimited texts to all networks+ Unlimited calls to Globe/TM+ 1GB per day for GoWATCH&PLAY and GoSHARE&SHOP','7 days','140'),
    ('GOCALL50','Globe','50 minutes calls to all networks','3 days','50'),
    ('GOCALL100','Globe','500 minutes calls to Globe or TM','7 days','100'),
    ('DUO','Globe','Unlimited calls to any Duo/MyDuo number, Globe Landline nationwide and selected landlines','30 days','450'),
    ('SUPERDUO','Globe','Unlimited calls to any Duo/MyDuo number, Globe Landline nationwide and selected landlines+ Unlimited calls to Globe or TM','30 days','599'),
    ('All Out Surf 20 ','Smart','150MB Internet Data+ 100MB data per day for Facebook+ Unlimited texts to all networks+ 20 minutes calls to Smart, TNT, SUN','1 Day',' 20'),
    ('All Out Surf 50','Smart','500MB Internet Data+ 100MB per day Facebook+ Unlimited texts to all networks+ 50 minutes calls to Smart, TNT, SUN','1 Day','50'),
    ('All Out Surf 99','Smart','1GB Internet Data+ 100MB per day Facebook+ Unlimited texts to all networks+ 100 minutes calls to Smart, TNT, SUN',' 7 days','99 Pesos'),
    ('UCT 25','Smart','Unlimited calls to SMART and TNT+ Unlimited texts to SMART, TNT and SUN+ 50 texts to other networks+ 30MB for Facebook','1 day','25 Pesos'),
    ('UCT 30','Smart','Unlimited calls to SMART, TNT and SUN+ Unlimited texts to all networks+ 100MB data for Facebook Messenger and WhatsApp',' 1 day',' 30 Pesos'),
    ('UCT 50','Smart','Unlimited calls to SMART, TNT and SUN+ Unlimited texts to all networks+ 300MB internet data for Facebook Messenger and WhatsApp','3 days','50 Pesos'),
    ('UCT 100','Smart','Unlimited calls to SMART, TNT and SUN+ Unlimited texts to all networks+ 500MB for Facebook Messenger and WhatsApp','7 days','100 Pesos'),
    ('UCT 350','Smart','Unlimited calls to SMART, TNT and SUN+ Unlimited texts to all networks+ 1GB data for Facebook Messenger and WhatsApp','30 days','350 Pesos'),
    ('CTS 15','Smart','Unlimited texts to all networks+ 20 minutes calls to Smart, SUN and TNT+ 100MB mobile data+ 100MB for Facebook and Instagram','1 day','15 Pesos'),
    ('CTS 29','Smart','300MB mobile data+ 100MB everyday for Instagram and Facebook+ Unlimited to Smart, TNT, SUN+ Unlimited texts to all networks','2 days','29 Pesos'),
    ('CTS 49','Smart','500MB mobile data+ 100MB everyday for Instagram and Facebook+ Unlimited to Smart, TNT, SUN+ Unlimited texts to all networks','3 days','49 Pesos'),
    ('CTS 109','Smart','Unlimited calls to Smart, TNT and SUN+ Unlimited texts to all networks+ 100MB everyday for Instagram and Facebook','15 days','109 Pesos'),
    ('Mega All-In 250','Smart','Unlimited texts to all networks+ 180 mins calls to Smart, SUN and TNT+ 100MB mobile data','30 days','250 Pesos'),
    ('GameTime 50','Smart','300MB everyday for ML, AoV, CoC and Clash Royale','7 days','50 Pesos'),
    ('GameTime 100','Smart','300MB everyday for ML, AoV, CoC and Clash Royale','30 days','100 Pesos'),
    ('Super Messaging 20 ','Smart','Unlimited texts to all networks+ 10 minutes calls to Smart, Sun and TNT+ Unlimited chats/access to FB Messenger, Whatsapp, Viber, WeChat and Line','1 days','20 Pesos'),
    ('Giga Music 50','Smart','1GB internet data+ 1GB per day on Spotify and Apple Music','3 days','50 Pesos'),
    ('Giga Music 99','Smart','2GB internet data+ 1GB per day on Spotify and Apple Music','7 days','99 Pesos'),
    ('Giga Music 299','Smart','4GB internet data+ 1GB per day on Spotify and Apple Music',' 30 days','299 Pesos'),
    ('Giga Games 50','Smart','1GB internet data+ 1GB per day on Mobile Legends, Clash of Clans, Call of Duty Mobile, Arena of Valor. Clash Royale and Facebook Gaming','3 days',' 50 Pesos'),
    ('Giga Games 99','Smart','2GB internet data+ 1GB per day on Mobile Legends, Clash of Clans, Call of Duty Mobile, Arena of Valor. Clash Royale and Facebook Gaming','7 days',' 99 Pesos'),
    ('Giga Games 299','Smart','4GB internet data+ 1GB per day on Mobile Legends, Clash of Clans, Call of Duty Mobile, Arena of Valor. Clash Royale and Facebook Gaming','30 days',' 299 Pesos'),
    ('Giga Games 399','Smart','6GB internet data+ 1GB per day on Mobile Legends, Clash of Clans, Call of Duty Mobile, Arena of Valor. Clash Royale and Facebook Gaming','30 days','399 Pesos'),
    ('Giga Games 499','Smart','8GB internet data+ 1GB per day on Mobile Legends, Clash of Clans, Call of Duty Mobile, Arena of Valor. Clash Royale and Facebook Gaming','30 days','499 Pesos'),
    ('Giga Video 50','Smart','1GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks','3 days','50 Pesos'),
    ('Giga Video 99','Smart','2GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV','7 days','99 Pesos'),
    ('Giga Video 299','Smart','4GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV','30 days','299 Pesos'),
    ('Giga Video 399','Smart','6GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV',' 30 days','399 Pesos'),
    ('Giga Video 499','Smart','8GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV','30 days','499 Pesos'),
    ('Giga Video+ 75','Smart','1GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks+ Unlimited calls to Smart, TNT and Sun Cellular','3 days','75 Pesos'),
    ('Giga Video+ 149','Smart','2GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks+ Unlimited calls to Smart, TNT and Sun Cellular','7 days','149 Pesos'),
    ('Giga Video+ 449','Smart','4GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks+ Unlimited calls to Smart, TNT and Sun Cellular','30 days','449 Pesos'),
    ('Giga Video+ 549','Smart','6GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks+ Unlimited calls to Smart, TNT and Sun Cellular','30 days','549 Pesos'),
    ('Giga Video+ 649','Smart','8GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks+ Unlimited calls to Smart, TNT and Sun Cellular',' 30 days','649 Pesos'),
    ('Giga Video+ AllNet 100','Smart','1GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks+ Unlimited calls to all networks','3 days','100 Pesos'),
    ('Giga Video+ AllNet 199','Smart','2GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks+ Unlimited calls to all networks','7 days','199 Pesos'),
    ('Giga Video+ AllNet 549','Smart','4GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks+ Unlimited calls to all networks','30 days','549 Pesos'),
    ('Giga Video+ AllNet 649','Smart','6GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks+ Unlimited calls to all networks','30 days','649 Pesos'),
    ('Giga Video+ AllNet 749','Smart','8GB internet data+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV+ Unlimited texts to all networks+ Unlimited calls to all networks','30 days','749 Pesos'),
    ('Giga Stories 50','Smart','1GB internet data+ 1GB per day on Instagram, Facebook, TikTok and Twitter','3 days','50 Pesos'),
    ('Giga Stories 99','Smart','2GB internet data+ 1GB per day on Instagram, Facebook, TikTok and Twitter','7 days','99 Pesos'),
    ('Giga Stories 299','Smart','4GB internet data+ 1GB per day on Instagram, Facebook, TikTok and Twitter','30 days','299 Pesos'),
    ('Giga Stories 399','Smart','6GB internet data+ 1GB per day on Instagram, Facebook, TikTok and Twitter','30 days','399 Pesos'),
    ('Giga Stories 499','Smart','8GB internet data+ 1GB per day on Instagram, Facebook, TikTok and Twitter','30 days','499 Pesos'),
    ('Giga Stories+ 75','Smart','1GB internet data+ 1GB per day on Instagram, Facebook, TikTok and Twitter+ Unlimited texts to all networks+ Unlimited calls to Smart, TNT and Sun Cellular','3 days','75 Pesos'),
    ('Giga Stories+ 149','Smart','2GB internet data+ 1GB per day on Instagram, Facebook, TikTok and Twitter+ Unlimited texts to all networks+ Unlimited calls to Smart, TNT and Sun Cellular','7 days','149 Pesos'),
    ('Giga Stories+ 449','Smart','4GB internet data+ 1GB per day on Instagram, Facebook, TikTok and Twitter+ Unlimited texts to all networks+ Unlimited calls to Smart, TNT and Sun Cellular','30 days','449 Pesos'),
    ('Giga Stories+ 549','Smart','6GB internet data+ 1GB per day on Instagram, Facebook, TikTok and Twitter+ Unlimited texts to all networks+ Unlimited calls to Smart, TNT and Sun Cellular','30 days','549 Pesos'),
    ('Giga Stories+ 649','Smart','8GB internet data+ 1GB per day on Instagram, Facebook, TikTok and Twitter+ Unlimited texts to all networks+ Unlimited calls to Smart, TNT and Sun Cellular','30 days','649 Pesos'),
    ('Giga Study 99','Smart','2GB internet data+ 1GB per day on Google Classroom, MS Teams, YouTube, Meet, G Suite, Google Search, Office 365, Canvas and NEO LMS','7 days','99 Pesos'),
    ('Giga Study 299','Smart','4GB internet data+ 1GB per day on Google Classroom, MS Teams, YouTube, Meet, G Suite, Google Search, Office 365, Canvas and NEO LMS','30 days','299 Pesos'),
    ('Giga Study 399','Smart','6GB internet data+ 1GB per day on Google Classroom, MS Teams, YouTube, Meet, G Suite, Google Search, Office 365, Canvas and NEO LMS','30 days','399 Pesos'),
    ('Giga Study 499','Smart','8GB internet data+ 1GB per day on Google Classroom, MS Teams, YouTube, Meet, G Suite, Google Search, Office 365, Canvas and NEO LMS','30 days','499 Pesos'),
    ('Giga Work 50','Smart','1GB internet data+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove','3 days','50 Pesos'),
    ('Giga Work 99','Smart','2GB internet data+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove','7 days','99 Pesos'),
    ('Giga Work 299','Smart','4GB internet data+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove','30 days','299 Pesos'),
    ('Giga Work 399','Smart','6GB internet data+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove','30 days','399 Pesos'),
    ('Giga Work 499','Smart','8GB internet data+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove','30 days','499 Pesos'),
    ('Giga Work+ ALLNET 100','Smart','1GB internet data+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove+ Unlimited calls and texts to all networks','3 days','100 Pesos'),
    ('Giga Work+ ALLNET 199','Smart','2GB internet data+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove+ Unlimited calls and texts to all networks','7 days','199 Pesos'),
    ('Giga Work+ ALLNET 549','Smart','4GB internet data+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove+ Unlimited calls and texts to all networks','30 days','549 Pesos'),
    ('Giga Work+ ALLNET 649','Smart','6GB internet data+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove+ Unlimited calls and texts to all networks','30 days','649 Pesos'),
    ('Giga Work+ ALLNET 749','Smart','8GB internet data+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove+ Unlimited calls and texts to all networks','30 days','749 Pesos'),
    ('GIGA K-VIDEO 50','Smart','1GB mobile data+ 1GB everyday for YouTube and Viu+ Free Viu Premium','7 days','199 Pesos'),
    ('GIGA PRO VIDEO 199','Smart','6GB mobile data+ 3GB everyday for YouTube, NBA and More (Total of 21 GB)','7 days','199 Pesos'),
    ('GIGA PRO VIDEO 599','Smart','12GB mobile data+ 3GB everyday for YouTube, NBA and More (Total of 45 GB)','15 days','599 Pesos'),
    ('GIGA PRO VIDEO 999','Smart','24GB mobile data+ 3GB everyday for YouTube, NBA and More (Total of 90 GB)','30 days',' 999 Pesos'),
    ('SULITXT5','TM','25 Texts to TM/Globe','1 day','5'),
    ('TXT10','TM','Unlimited texts to TM/Globe',' 2 days','10'),
    ('UNLIALLNET10','TM','Unlimited texts to all networks','1 day','10'),
    ('ASTIGTXT30','TM','Unlimited texts to TM/Globe',' 5 days','30'),
    ('UNLITAWAG15','TM','Unlimited calls to TM/Globe','1 day','15'),
    ('TXT5 ','TM','Add-on to UNLITAWAG15 that extends the promo validity for another 1 day','1 day','5'),
    ('DAGDAGTXT(add-on)','TM','Add-on to UNLITAWAG15 for an additional 100 Texts to all networks','1 day','5'),
    ('EXTEND5(add-on)','TM','Add-on that extends all unlimited call and text promos for another 1 day up to 365 days','1 day','5'),
    ('COMBOALL10','TM','Unlimited calls to TM/Globe+ Unlimited texts to TM/Globe+ 50 texts to all networks','1 day','10'),
    ('COMBOALL20','TM','Unlimited calls to TM/Globe+ Unlimited texts to TM/Globe+ 50 texts to all networks','3 days','20'),
    ('COMBO15','TM','Unlimited texts to all networks+ 120 minutes calls to TM/Globe','2 days','15'),
    ('COMBO20','TM','Unlimited texts to all networks+ 120 minutes calls to TM/Globe','3 days','20'),
    ('ML10','TM','1GB for Mobile Legends','3 days','10'),
    ('FB10','TM','1GB for Facebook','3 days','10'),
    ('FB15','TM','200MB for Facebook','2 days','15'),
    ('FB30','TM','300MB for Facebook+Unlimited texts to all networks',' 3 days','30'),
    ('FB50','TM','500MB for Facebook+Unlimited texts to all networks',' 5 days','50'),
    ('FACEBOOK50','TM','600MB for Facebook','7 days','50'),
    ('FB199','TM','1GB for Facebook','30 days','199'),
    ('EASYSURF10','TM','40MB data','1 day','10'),
    ('EASYSURF15','TM','100MB data+ 30MB for Instagram','2 days','15'),
    ('EASYSURF30','TM','300MB data+ 50MB for Facebook, Viber or Snapchat','2 days','30'),
    ('EASYSURF50','TM','2GB data+ 1GB everyday for App of Choice (Facebook, YouTube, Mobile Legends, TikTok, etc.)+ Unlimited texts to all networks','3 days','50'),
    ('EASYSURF 70','TM','1GB data+ 1GB for App of Bundle (Facebook, YouTube, Mobile Legends, TikTok, etc.) per day(7GB total).+ Unlimited texts to all networks','7 days','70'),
    ('EASYSURF 90','TM','2GB data+ 1GB everyday for App of Bundle (7GB total)+ Unlimited texts to all networks','7 days','90'),
    ('EASYSURF299','TM','2GB mobile data+ 10GB for App Bundle','30 days','299'),
    ('EASYSURF599','TM','5GB data+ 10GB for App Bundle','30 days','599'),
    ('EASYSURF999','TM','10GB data+ 10GB for App Bundle','30 days','999'),
    ('EASYSURF1299','TM','15GB data+ 10GB for App Bundle','30 days','1299'),
    ('EASYSURF1999','TM','30GB data+ 10GB for App Bundle','30 days','1999'),
    ('EASYSURF2499','TM','50GB data+ 10GB for App Bundle','30 days','2499'),
    ('GG30','TM','300MB for Games+ Unlimited texts to all networks',' 3 days','30'),
    ('GG50','TM','500MB for Games+ Unlimited texts to all networks','5 days','50'),
    ('GAMES15','TM','100MB game apps data',' 1 day','15'),
    ('GAMES20','TM','100MB for Games','2 days','20'),
    ('GAMES50','TM','300MB for Games','7 days','50'),
    ('GAMES99','TM','300MB for Games','30 days','99'),
    ('FS FBIG','TM','400MB for Facebook and Instagram',' No Expiry','10'),
    ('FS YTML','TM','400MB for YouTube and Mobile Legends','No Expiry','10'),
    ('FS TikWS','TM','400MB for TikTok and WeSing','No Expiry','10'),
    ('FS iWCOD','TM','400MB for iWant and Call of Duty','No Expiry','10'),
    ('A20TY/AS20Y','TM','Unlimited calls to TM/Globe+ Unlimited texts to all networks+ 200MB data+ 100MB YouTube data','2 days','20'),
    ('A20FB/AS20FB','TM','Unlimited calls to TM/Globe+ Unlimited texts to all networks+ 200MB data+ 100MB Facebook data','2 days','20'),
    ('A20ML/AS20ML','TM','Unlimited calls to TM/Globe+ Unlimited texts to all networks+ 200MB data+ 100MB Mobile Legends data','2 days','20'),
    ('A20WP/AS20WP','TM','Unlimited calls to TM/Globe+ Unlimited texts to all networks+ 200MB data+ 100MB Wattpad data','2 days','20'),
    ('SUPERSURF50','TM','Unlimited mobile internet','1 day','50'),
    ('SUPERSURF200','TM','Unlimited mobile internet','5 days','200'),
    ('All-In Surf 30','TM','300MB data+700MB for Facebook, YouTube, TikTok, WeSing, iWant and Mobile Legends','3 days','30'),
    ('Winner Text 10','Sun','Unlimited texts to Sun+ 10 minutes calls to Sun, Smart, and Talk ‘N Text+ Facebook access','1 Day','10'),
    ('TRINET 20','Sun','Unlimited texts to Sun, Smart and TNT+ 50 texts to other networks+ 60 minutes calls to Sun, Smart and TNT+ 30MB Facebook per day','3 Days','20'),
    ('Call Unlimited 30','Sun','Unlimited calls to Sun+ 50 texts to all networks+ Facebook access+ Non-Stop Chat','2 Days','30'),
    ('Text All 30','Sun','Unlimited texts to all networks+ Facebook access+ Non-Stop Chat','3 Days','30'),
    ('Call and Text Combo 10','Sun','10 minutes calls to Sun, Smart, and Talk ‘N Text+ 50 texts to Sun+ 50 texts to other networks+ Facebook access','1 Day','10'),
    ('Call and Text Combo 20','Sun','25 minutes calls to Sun, Smart, and Talk ‘N Text+ 100 texts to Sun+ 100 texts to other networks+ Facebook access','3 Days','20'),
    ('Call and Text Combo 30','Sun','40 minutes calls to Sun, Smart, and Talk ‘N Text+ 150 texts to Sun Cellular+ 150 texts to other networks+ Facebook access+ Non-Stop Chat',' 3 Days','30'),
    ('Call and Text Combo 50','Sun','70 minutes calls to Sun, Smart, and Talk ‘N Text+ 250 texts to Sun+ 250 texts to other networks+ Facebook access+ Non-Stop Chat','5 Days','50'),
    ('Text Unlimited 20','Sun','Unlimited texts to Sun+ 50 texts to other networks+ 20 minutes calls Sun, Smart, and Talk ‘N Text+ Facebook access','3 Days','20'),
    ('Text Unlimited 50','Sun','Unlimited texts to Sun+ 60 minutes calls to Sun+ Facebook access+ Non-Stop Cha','10 Days','50'),
    ('Text Unlimited 60','Sun','Unlimited texts to Sun+ 60 minutes calls to Sun, Smart, and Talk ‘N Text+ 200 texts to other networks+ Facebook access+ Non-Stop Chat','10 Days','60'),
    ('Text Unlimited 150','Sun','Unlimited texts to Sun+ 5 hours calls to Sun+ Facebook access+ Non-Stop Chat+ Spinnr access','30 Days','150'),
    ('Text Unlimited 200','Sun',' Unlimited texts to Sun+ 5 Hours calls to PLDT, Sun, Smart, Talk ‘N Text+ 1,000 texts to other networks+ Facebook access+ Non-Stop Chat','30 Days','200'),
    ('Text Unlimited 300','Sun','Unlimited texts to Sun+ 10 hours calls to Sun, Smart, and Talk ‘N Text+ 3,000 texts to other networks+ Facebook access+ Spinnr access+ Non-Stop Chat','30 Days','300'),
    ('Non-Stop Surf 25','Sun','Non-stop Mobile Internet Surfing+ 25MB Internet Data+ 300MB Spinnr Access and Streaming','1 Day','25'),
    ('Non-Stop Surf 50','Sun','Non-stop Mobile Internet Surfing+ 100MB Internet Data+ 500MB Spinnr Access and Streaming','3 Days','50'),
    ('Non-Stop Surf 100','Sun','Non-stop Mobile Internet Surfing+ 250MB Internet Data+ 1GB Spinnr Access and Streaming',' 5 Days','100'),
    ('Non-Stop Surf 299','Sun','Non-stop Mobile Internet Surfing+ 1GB Spinnr','30 Days','299'),
    ('Non-Stop Surf 450','Sun','Non-stop Mobile Internet Surfing+ 1GB Internet Data+ 1GB Spinnr','30 Days','450'),
    ('Non-Stop Surf 699','Sun','Non-stop Mobile Internet Surfing+ 2.5GB Internet Data+ 1GB Spinnr','30 Days','699'),
    ('Call and Text Unlimited 25','Sun','Unlimited calls to Sun+ Unlimited texts to all networks+ Facebook access','1 Day','25'),
    ('Call and Text Unlimited 30','Sun','Unlimited calls to Sun, Smart and Talk ‘N Text+ Unlimited texts to all networks+ Facebook access+ Non-Stop Chat','1 Day','30'),
    ('Call and Text Unlimited 50','Sun',' Unlimited calls to Sun, Smart and Talk ‘N Text+ Unlimited texts to all networks+ Facebook access+ Non-Stop Chat','3 Days','50'),
    ('Call and Text Unlimited 100','Sun',' Unlimited calls to Sun, Smart and Talk ‘N Text+ Unlimited texts to all networks+ 100MB internet data','7 Days','100'),
    ('Call and Text Unlimited 150','Sun','Unlimited calls to Sun, Smart and TNT+ Unlimited texts to all networks+ 500MB data',' 7 Days','150'),
    ('Call and Text Unlimited 450','Sun',' Unlimited calls Sun, Smart, and Talk ‘N Text+ Unlimited texts to all networks+ 1.5GB data','30 Days','450'),
    ('Wais 100','Sun','Unlimited calls to Sun Cellular+ Unlimited texts to Sun Cellular','15 Days','100'),
    ('Wais 200','Sun','Unlimited calls to Sun Cellular+ Unlimited texts to Sun Cellular+ 500 texts to Smart and TNT','30 Days','200'),
    ('MB5','Sun','10MB data','1 Day','5'),
    ('MB50','Sun','100MB Internet Data Allocation+ 500MB Spinnr','3 Days','50'),
    ('MB99','Sun','200MB Internet Data Allocation+ 1GB Spinnr','30 Days','99'),
    ('MB250','Sun','700MB Internet Data Allocation+ 1GB Spinnr','30 Days','250'),
    ('Photo Bundle 10','Sun','Access to Instagram, Flicker, Pinterest and Tumblr','1 Day','10'),
    ('Photo Bundle 199','Sun','Access to Instagram, Flicker, Pinterest and Tumblr','30 Days','199'),
    ('Social Bundle 10','Sun','Access to Facebook, Twitter, Google Plus, Waze, Foursquare, Linkedln and Path','1 Day','10'),
    ('Social Bundle 199','Sun','Access to Facebook, Twitter, Google Plus, Waze, Foursquare, Linkedln and Path','30 Days','199'),
    ('Email Bundle 10','Sun','Access to Gmail, Yahoo Mail, Outlook and Exchange','1 Day','10'),
    ('Chat Bundle 10','Sun','Access to Facebook Messenger, Chikka Messenger, Line, WeChat, WhatsApp, Viber, Kakao and Oist',' 1 Day','10'),
    ('Email Bundle 199','Sun','Access to Gmail, Yahoo Mail, Outlook and Exchange','30 Days','199'),
    ('Chat Bundle 249','Sun','Access to Facebook Messenger, Chikka Messenger, Line, WeChat, WhatsApp, Viber, Kakao and Oist','30 Days','249'),
    ('GIGASURF50','Sun','1GB open access data+ 300MB YouTube+ Unlimited texts to all networks','3 Days','50'),
    ('Big Time Data 70','Sun','1GB internet data+ 30 minutes calls to Sun+ Unlimited texts to all networks','7 Days','70'),
    ('SURFSAYA FB 20','TNT','100MB data+ 100MB everyday of Facebook and Messenger+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','2 days','20'),
    ('SURFSAYA FB 30','TNT',' 300MB data+ 100MB everyday for Facebook and Messenger+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun+ (BONUS) Unlimited calls to all networks','3 days','30'),
    ('SURFSAYA FB 99','TNT','1.5GB data+ 100MB everyday for Facebook and Messenger+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun+ (BONUS) Unlimited calls to all networks','7 days','99'),
    ('SURFSAYA FB 199','TNT','2GB data+ 200MB everyday for Facebook and Messenger+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun+ (BONUS) Unlimited calls to all networks','30 days','199'),
    ('SURFSAYA ML 20','TNT',' 100MB data+ 100MB everyday for Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','2 days','20'),
    ('SURFSAYA ML 30','TNT','300MB data+ 100MB everyday for Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','3 days','30'),
    ('SURFSAYA ML 99','TNT','1.5GB data+ 100MB everyday for Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','7 days','99'),
    ('SURFSAYA ML 199','TNT','2GB data+ 200MB everyday for Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','30 days','199'),
    ('SURFSAYA ALLNET 40','TNT','100MB data+ 100MB everyday for Facebook and Messenger+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun/Globe/TM',' 2 days','40'),
    ('SURFSAYA ALLNET 55','TNT',' 300MB data+ 100MB everyday for Facebook and Messenger+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun/Globe/TM','3 days','55'),
    ('SURFSAYA ALLNET 149','TNT','1.5GB data+ 100MB everyday for Facebook and Messenger+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun/Globe/TM','7 days','149'),
    ('SURFSAYA ALLNET 319','TNT','2GB data+ 200MB everyday for Facebook and Messenger+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun/Globe/TM','30 days','319'),
    ('SURFSAYA ALL-IN 45','TNT',' 100MB data+ 100MB everyday for Facebook, Instagram and Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun/Globe/TM','2 days','45'),
    ('SURFSAYA ALL-IN 60','TNT','300MB data+ 100MB everyday for Facebook, Instagram and Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun/Globe/TM','3 days','60'),
    ('SURFSAYA ALL-IN 159','TNT','1.5GB data+ 100MB everyday for Facebook, Instagram and Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun/Globe/TM','7 days','159'),
    ('SURFSAYA ALL-IN 349','TNT','2GB data+ 200MB everyday for Facebook, Instagram and Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun/Globe/TM','30 days','349'),
    ('SURFSAYA FB+ML 30','TNT','100MB data+ 100MB everyday you can consume for Facebook and/or Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','2 days','30'),
    ('SURFSAYA FB+ML 45','TNT','300MB data+ 100MB everyday you can consume for Facebook and/or Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','3 days','45'),
    ('SURFSAYA FB+ML 129','TNT','1.5GB data+ 100MB everyday you can consume for Facebook and/or Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','7 days','129'),
    ('SURFSAYA FB+ML 259','TNT','2GB data+ 200MB everyday you can consume for Facebook and/or Mobile Legends+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','30 days','259'),
    ('SURFSAYA FB+IG 35','TNT','100MB data+ 100MB everyday you can consume for Facebook and/or Instagram+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','2 days','35'),
    ('SURFSAYA FB+IG 50','TNT','300MB data+ 100MB everyday you can consume for Facebook and/or Instagram+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun',' 3 days','50'),
    ('SURFSAYA FB+IG 139','TNT','1.5GB data+ 100MB everyday you can consume for Facebook and/or Instagram+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','7 days','139'),
    ('SURFSAYA FB+IG 289','TNT','2GB data+ 200MB everyday you can consume for Facebook and/or Instagram+ Unlimited texts to all networks+ Unlimited calls to TNT/SMART/Sun','30 days','289'),
    ('GIGA VIDEO 50','TNT','1GB data+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play+ Unlimited texts to all networks','3 days','50'),
    ('GIGA VIDEO 99','TNT','2GB data+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play','7 days','99'),
    ('GIGA VIDEO 299','TNT',' 4GB data+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play','30 days','299'),
    ('GIGA VIDEO 399','TNT','6GB data+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play','30 days','399'),
    ('GIGA VIDEO 499','TNT',' 8GB data+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play','30 days','499'),
    ('GIGA VIDEO+ 75','TNT',' 1GB data+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play+ Unlimited calls to Smart/TNT/Sun+ Unlimited texts to all networks','3 days','75'),
    ('GIGA VIDEO+ 149','TNT','2GB data+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play+ Unlimited calls to Smart/TNT/Sun+ Unlimited texts to all networks',' 7 days','149'),
    ('GIGA VIDEO+ 449','TNT','4GB data+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play+ Unlimited calls to Smart/TNT/Sun+ Unlimited texts to all networks','30 days','449'),
    ('GIGA VIDEO+ 549','TNT','6GB data+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play+ Unlimited calls to Smart/TNT/Sun+ Unlimited texts to all networks','30 days','549'),
    ('GIGA VIDEO+ 649','TNT','8GB data+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play+ Unlimited calls to Smart/TNT/Sun+ Unlimited texts to all networks','30 days','649'),
    ('GIGA GAMES 50','TNT','1GB data+ 1GB per day you can consume to play Mobile Legends, FB Gaming, Clash of Clans, Arena of Valor and Clash Royale','3 days','50'),
    ('GIGA GAMES 99','TNT','2GB data+ 1GB per day you can consume to play Mobile Legends, FB Gaming, Clash of Clans, Arena of Valor and Clash Royale','7 days','99'),
    ('GIGA GAMES 299','TNT','4GB data+ 1GB per day you can consume to play Mobile Legends, FB Gaming, Clash of Clans, Arena of Valor and Clash Royale','30 days','299'),
    ('GIGA GAMES 399','TNT','6GB data+ 1GB per day you can consume to play Mobile Legends, FB Gaming, Clash of Clans, Arena of Valor and Clash Royale','30 days','399'),
    ('GIGA GAMES 499','TNT','8GB data+ 1GB per day you can consume to play Mobile Legends, FB Gaming, Clash of Clans, Arena of Valor and Clash Royale','30 days','499'),
    ('GIGA STORIES 50','TNT','1GB data+ 1GB per day you can consume for TikTok, Facebook, Instagram and Twitter','3 days','50'),
    ('GIGA STORIES 99','TNT','2GB data+ 1GB per day you can consume for TikTok, Facebook, Instagram and Twitter','7 days','99'),
    ('GIGA STORIES 299','TNT','4GB data+ 1GB per day you can consume for TikTok, Facebook, Instagram and Twitter','30 days','299'),
    ('GIGA STORIES 399','TNT','6GB data+ 1GB per day you can consume for TikTok, Facebook, Instagram and Twitter','30 days','399'),
    ('GIGA STORIES 499','TNT','8GB data+ 1GB per day you can consume for TikTok, Facebook, Instagram and Twitter',' 30 days','499'),
    ('GIGA STUDY 99','TNT','2GB data+ 1GB per day for Google Classroom, Google Meet, G Suite, Google Search, MS Teams, YouTube', '7 days','99'),
    ('GIGA STUDY 299','TNT','4GB data+ 1GB per day for Google Classroom, Google Meet, G Suite, Google Search, MS Teams, YouTube','30 days','299'),
    ('GIGA WORK 50','TNT','1GB data+ 1GB per day for Grab, Lazada, Shopee, Paymaya, and more.','3 days','50'),
    ('GIGA WORK 99','TNT','2GB data+ 1GB per day for Grab, Lazada, Shopee, Paymaya, and more.','7 days','99'),
    ('GIGA WORK 299','TNT','4GB data+ 1GB per day for Grab, Lazada, Shopee, Paymaya, and more.','30 days','299'),
    ('Gaan Surf 5','TNT','15MB data','1 day','5'),
    ('Gaan Surf 10','TNT','50MB data+ 100MB for Facebook, YouTube and Mobile Legends','1 day','10'),
    ('Gaan Text 10','TNT','Unlimited texts to all networks','1 day','10'),
    ('Clash of Clans 10','TNT','Access to Clash of Clans','3 days','10'),
    ('Facebook 10','TNT','Access to Facebook','3 days','10'),
    ('Mobile Legends 10','TNT','Access to Mobile Legends','3 days','10'),
    ('Alden & Maine Load 15','TNT','Unlimited texts to all networks+ 60 minutes calls to TNT/Smart/Sun+ 100MB Facebook, Twitter, Viber, Clash of Clans and Dubsmash','1 day','15'),
    ('Gaan Surf 15','TNT','100MB data+ 100MB for Facebook, YouTube and Mobile Legends','2 days','15'),
    ('Gaan Text 20','TNT','Unlimited texts to all networks','2 days','20'),
    ('Super Combo 20','TNT','Unlimited calls and unlimited texts to TNT/Smart/Sun+ 50MB data','2 days','20'),
    ('Unli Talk and Text 20','TNT','Unlimited texts to all networks+ Unlimited calls to TNT/Smart/Sun+ 100MB of Tropa Apps','1 day','20'),
    ('Unli Text 20','TNT','Unlimited texts to TNT/Smart/Sun+ 20 minutes calls to TNT/Smart/Sun+ 50 texts to other networks','3 days','20'),
    ('All Day 20','TNT','800MB data but downloading and video streaming is unavailable','1 day','20'),
    ('Unlitext2All Plus 25','TNT','Unlimited texts to all networks+ 60 minutes calls to TNT/Smart/Sun+ 100MB Facebook, Twitter, Viber, Clash of Clans and Dubsmash','3 days','25'),
    ('Unli All-Net Text 30','TNT','Unlimited texts to all networks','5 days','30'),
    ('All Day 30','TNT','500MB access to all sites except video streaming and downloading','2 days','30'),
    ('Gaan Surf 30','TNT','300MB data+ 200MB for Facebook, YouTube and Mobile Legends','5 days','30'),
    ('Panalo Data 30','TNT','500MB data+ 200MB for Facebook per day','2 days','30'),
    ('Panalo Combo 30','TNT','200MB data+ 60 minutes calls to TNT/Smart/Sun+ Unlimited texts to all networks','3 days','30'),
    ('All Out Surf 30','TNT','300MB data+ 30 minutes calls to TNT/Smart/Sun+ Unlimited texts to all networks','2 days','30'),
    ('Panalo 40','TNT','Unlimited texts to all networks+ Unlimited calls to TNT/Smart/Sun(Available only in North and Central Luzon, Visayas, and Mindanao provinces)','7 days','40'),
    ('Unlitext2All Plus 50','TNT','Unlimited texts to all networks+ 150 minutes calls to TNT/Smart/Sun','5 days','50'),
    ('Gaan Surf 50','TNT','500MB data+ 200MB for Facebook, YouTube and Mobile Legends','7 days','50'),
    ('Giga Surf 50','TNT','1GB data+ 300MB YouTube+ Unlimited texts to all networks','1 day','50'),
    ('Surf Max 50','TNT','800MB data','1 day','50'),
    ('Unli All-Net Text 60','TNT','Unlimited texts to all networks+ 150 minutes calls to TNT/Smart/Sun+ 150MB of Tropa Apps','7 days','60'),
    ('Panalo Data 60','TNT','1GB data+ Unlimited texts to all networks','5 days','60'),
    ('Panalo Combo 60','TNT','500MB data+ 100 minutes calls to TNT/Smart/Sun+ Unlimited texts to all networks','7 days','60'),
    ('Super Combo 70','TNT','300MB data+ Unlimited calls to TNT/Smart/Sun+ Unlimited texts to TNT/Smart/Sun','5 days','70'),
    ('Clash of Clans 99','TNT','1.5GB for Clash of Clans','30 days','99'),
    ('Facebook 99','TNT','1.5GB for Facebook','30 days','99'),
    ('YouTube 99','TNT','1.5GB for YouTube','30 days','99'),
    ('Unli Talk and Text 100','TNT','Unlimited texts to all networks+ Unlimited calls to TNT/Smart/Sun+ 100MB Tropa Apps','7 days','100'),
    ('UTP150','TNT','Unlimited texts to TNT/Smart/Sun+ 150 minutes calls to TNT/Smart/Sun+ 150 texts to other networks','30 days','150'),
    ('TROPA 150','TNT','Unlimited texts to all networks+ 60 minutes calls to TNT/Smart per day+ 100MB for Facebook, Twitter, COC, Dubsmash and Viber per day','15 days','150'),
    ('Gaan Surf 150','TNT','1.5GB data+ 750MB for Facebook, YouTube and Mobile Legends','30 days','150'),
    ('Surf Max 299','TNT','800MB data per day','7 days','299'),
    ('UA300','TNT','Unlimited texts to all networks+ 300 minutes calls to TNT/Smart/Sun','30 days','300'),
    ('Surf Max 999','TNT','800MB data per day','30 days','999');";


if ($conn->multi_query($sql) === TRUE) {
  echo "New records created successfully";
} else {
  echo "Error: " . $sql . "<br>" . $conn->error;
}

$conn->close();
?>
