
<?php
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "loade";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}

$sql = '';
$sql .= "INSERT INTO history (num,promo,cost,date_purc,date_exp)
VALUES ('09983023652','GigaSurf99','99','May 30','June 7');";
$sql .= "INSERT INTO users (num,name,sim_prov,regdate)
VALUES ('09983023652','Andre Cal','SMART','May 30');";
$sql .= "INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF10','Globe','40MB internet data','1 day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF15','Globe','\"100MB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 30MB for Instragram\"','2 days','15');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF30','Globe','\"300MB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50MB for Facebook, Instagram, Viber or SnapChat\"','2 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF50','Globe','\"2GB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB for GoWATCH & PLAY, GoSHARE & SHOP, GoLISTEN & TRAVEL, or GoLEARN & WORK');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF99','Globe','\"200MB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB for app of choice\"','30 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF199','Globe','\"500MB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB for app of choice\"','30 days','199');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF299','Globe','\"2GB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10GB for GoWATCH & PLAY, GoSHARE & SHOP, GoLISTEN & TRAVEL, or GoLEARN & WORK\"','30 days','299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF499','Globe','\"3GB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB for app of choice\"','30 days','499');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF599','Globe','\"5GB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10GB for GoWATCH & PLAY, GoSHARE & SHOP, GoLISTEN & TRAVEL, or GoLEARN & WORK\"','30 days','599');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF999','Globe','\"10GB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10GB for app bundle\"','30 days','999');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSURF1299','Globe','\"15GB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10GB for app bundle\"','30 days','1299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UNLI10','Globe','Unlimited calls and texts to Globe or TM','1 day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SULITXT15','Globe','100 texts to Globe or TM','1 day','15');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOUNLI20','Globe','\"Unlimited calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 20MB internet data\"','1 day','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOUNLI25','Globe','\"Unlimited calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ FREE Unlimited Viber\"','1 day','25');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOUNLI30','Globe','\"Unlimited calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 30MB internet data\"','2 day','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOUNLI50','Globe','\"Unlimited calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 MB mobile internet\"','3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOUNLI95','Globe','\"Unlimited calls to Globe and TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB internet data\"','7 days','95');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOUNLI180','Globe','\"Unlimited calls to Globe and TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 150MB internet data\"','15 days','180');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOUNLI350','Globe','\"Unlimited calls to Globe and TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB internet data\"','30 days','350');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Tawag 236','Globe','20 minutes calls to Globe or TM for ₱20','20 minutes','Requires at least ₱7.50 load');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('ATXT20','Globe','250 texts to all networks','1 day','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UNLITXT20','Globe','Unlimited texts to Globe or TM','1 day','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UNLITXT40','Globe','Unlimited texts to Globe or TM','2 days','40');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOUNLITXT49','Globe','Unlimited texts to Globe or TM','7 days','49');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UNLITXT80','Globe','Unlimited texts to Globe or TM','5 days','80');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('ATXTPLUS20','Globe','\"10 minutes calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 250 texts to all networks\"','1 day','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Games 15','Globe','100MB for games (see Game Bundle Apps below)','1 day','15');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Games 20','Globe','100MB for games (see Game Bundle Apps below)','2 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Games 50','Globe','300MB for games (see Game Bundle Apps below)','7 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Games 99','Globe','300MB for games (see Game Bundle Apps below)','30 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UALLPLUS25','Globe','\"Unlimited calls to Globe and TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to Globe and TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1 hour mobile internet\"','1 day','25');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOALLNET25','Globe','\"Unlimited texts to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 75 minutes calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 5 MB for Facebook\"','1 day','25');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOALLNET30','Globe','\"Unlimited calls and texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB mobile data\"','1 day','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOALLNET50','Globe','\"Unlimited calls and texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 300MB mobile data\"','3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOALLNET70','Globe','\"Unlimited texts to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 115 minutes calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 5MB for Facebook\"','3 days','70');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOALLNET200','Globe','\"Unlimited texts to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 410 minutes calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10 MB for Facebook\"','7 days','200');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOALLNET300','Globe','\"Unlimited texts to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 580 minutes calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10MB for Facebook\"','15 days','300');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOALLNET500','Globe','\"Unlimited texts to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 710 minutes calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10 MB for Facebook\"',' 30 days','500');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOTSCOMBOKEA37','Globe','\"1GB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 20 texts to all networks\"','1 day','37');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GO19','Globe','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 20 minutes calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 15MB internet data\"','1 day','19');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Go50','Globe','\"5GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Go90','Globe','\"8GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','7 days','90');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Go120','Globe','\"10GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Globe or TM\"','7 days','120');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Go140','Globe','\"11GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Globe or TM\"','7 days','140');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSAKTO70/GOTSCOMBODD70','Globe','\"1GB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day for GoWATCH&PLAY and GoSHARE&SHOP\"','7 days','70');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSAKTO90/GOTSCOMBODD90','Globe','\"2GB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day for GoWATCH&PLAY and GoSHARE&SHOP\"','7 days','90');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOSAKTO120','Globe','\"3GB of mobile internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Globe or TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day for GoWATCH&PLAY and GoSHARE&SHOP\"','7 days','120');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GoSAKTO140','Globe','\"4GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Globe/TM');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day for GoWATCH&PLAY and GoSHARE&SHOP\"','7 days','140');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOCALL50','Globe','50 minutes calls to all networks','3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GOCALL100','Globe','500 minutes calls to Globe or TM','7 days','100');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('DUO','Globe','Unlimited calls to any Duo/MyDuo number, Globe Landline nationwide and selected landlines','30 days','450');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SUPERDUO','Globe','\"Unlimited calls to any Duo/MyDuo number, Globe Landline nationwide and selected landlines');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Globe or TM\"','30 days','599');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('All out Surf 20 ','Smart','\"150MB Internet Data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB data per day for Facebook');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 20 minutes calls to Smart, TNT, SUN\"','20 Pesos',' 1 day');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('All Out Surf 50','Smart','\"500MB Internet Data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB per day Facebook');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 minutes calls to Smart, TNT, SUN\"','50 pesos ','3 Days');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('All Out Surf 99','Smart','\"1GB Internet Data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB per day Facebook');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100 minutes calls to Smart, TNT, SUN\"',' 7 days','99 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UCT 25','Smart','\"Unlimited calls to SMART and TNT');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to SMART, TNT and SUN');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 texts to other networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 30MB for Facebook\"','1 day','25 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UCT 30','Smart','\"Unlimited calls to SMART, TNT and SUN');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB data for Facebook Messenger and WhatsApp\"',' 1 day',' 30 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UCT 50','Smart','\"Unlimited calls to SMART, TNT and SUN');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 300MB internet data for Facebook Messenger and WhatsApp\"','3 days','50 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UCT 100','Smart','\"Unlimited calls to SMART, TNT and SUN');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 500MB for Facebook Messenger and WhatsApp\"','7 days','100 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UCT 350','Smart','\"Unlimited calls to SMART, TNT and SUN');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB data for Facebook Messenger and WhatsApp\"','30 days','350 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('CTS 15','Smart','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 20 minutes calls to Smart, SUN and TNT');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB mobile data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB for Facebook and Instagram\"','1 day','15 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('CTS 29','Smart','\"300MB mobile data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Instagram and Facebook');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited to Smart, TNT, SUN');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"',' 2 days validity','29 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('CTS 49','Smart','\"500MB mobile data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Instagram and Facebook');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited to Smart, TNT, SUN');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','3 days','49 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('CTS 109','Smart','\"Unlimited calls to Smart, TNT and SUN');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Instagram and Facebook\"','15 days','109 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Mega All-In 250','Smart','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 180 mins calls to Smart, SUN and TNT');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB mobile data\"','30 days','250 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GameTime 50','Smart','300MB everyday for ML, AoV, CoC and Clash Royale','7 days','50 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GameTime 100','Smart','300MB everyday for ML, AoV, CoC and Clash Royale','30 days','100 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Super Messaging 20 ','Smart','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10 minutes calls to Smart, Sun and TNT');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited chats/access to FB Messenger, Whatsapp, Viber, WeChat and Line\"','1 days','20 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Music 50','Smart','\"1GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Spotify and Apple Music\"','3 days','50 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('\"Giga Music 99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('\"','Smart','\"2GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Spotify and Apple Music\"','7 days','99 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Music 299','Smart','\"4GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Spotify and Apple Music\"',' 30 days','299 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Games 50','Smart','\"1GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Mobile Legends, Clash of Clans, Call of Duty Mobile, Arena of Valor. Clash Royale and Facebook Gaming\"','3 days',' 50 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Games 99','Smart','\"2GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Mobile Legends, Clash of Clans, Call of Duty Mobile, Arena of Valor. Clash Royale and Facebook Gaming\"','7 days',' 99 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Games 299','Smart','\"4GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Mobile Legends, Clash of Clans, Call of Duty Mobile, Arena of Valor. Clash Royale and Facebook Gaming\"','30 days',' 299 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Games 399','Smart','\"6GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Mobile Legends, Clash of Clans, Call of Duty Mobile, Arena of Valor. Clash Royale and Facebook Gaming\"','30 days','399 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Games 499','Smart','\"8GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Mobile Legends, Clash of Clans, Call of Duty Mobile, Arena of Valor. Clash Royale and Facebook Gaming\"','30 days','499 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video 50','Smart','\"1GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','3 days','50 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video 99','Smart','\"2GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV\"','7 days','99 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video 299','Smart','\"4GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV\"','30 days','299 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video 399','Smart','\"6GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV\"',' 30 days','399 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video 499','Smart','\"8GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV\"','30 days','499 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video+ 75','Smart','\"1GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart, TNT and Sun Cellular\"','3 days','75 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video+ 149','Smart','\"2GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart, TNT and Sun Cellular\"','7 days','149 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video+ 449','Smart','\"4GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart, TNT and Sun Cellular\"','30 days','449 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video+ 549','Smart','\"6GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart, TNT and Sun Cellular\"','30 days','549 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video+ 649','Smart','\"8GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart, TNT and Sun Cellular\"',' 30 days','649 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video+ AllNet 100','Smart','\"1GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to all networks\"','3 days','100 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video+ AllNet 199','Smart','\"2GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to all networks\"','7 days','199 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video+ AllNet 549','Smart','\"4GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to all networks\"','30 days','549 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video+ AllNet 649','Smart','\"6GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to all networks\"','30 days','649 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Video+ AllNet 749','Smart','\"8GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on YouTube, NBA League Pass, iflix, iWant TV and Cignal TV');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to all networks\"','30 days','749 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Stories 50','Smart','\"1GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Instagram, Facebook, TikTok and Twitter\"','3 days','50 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Stories 99','Smart','\"2GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Instagram, Facebook, TikTok and Twitter\"','7 days','99 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Stories 299','Smart','\"4GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Instagram, Facebook, TikTok and Twitter\"','30 days','299 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Stories 399','Smart','\"6GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Instagram, Facebook, TikTok and Twitter\"','30 days','399 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Stories 499','Smart','\"8GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Instagram, Facebook, TikTok and Twitter\"','30 days','499 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Stories+ 75','Smart','\"1GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Instagram, Facebook, TikTok and Twitter');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart, TNT and Sun Cellular\"','3 days','75 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Stories+ 149','Smart','\"2GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Instagram, Facebook, TikTok and Twitter');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart, TNT and Sun Cellular\"','7 days','149 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Stories+ 449','Smart','\"4GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Instagram, Facebook, TikTok and Twitter');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart, TNT and Sun Cellular\"','30 days','449 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Stories+ 549','Smart','\"6GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Instagram, Facebook, TikTok and Twitter');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart, TNT and Sun Cellular\"','30 days','549 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Stories+ 649','Smart','\"8GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Instagram, Facebook, TikTok and Twitter');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart, TNT and Sun Cellular\"','30 days','649 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Study 99','Smart','\"2GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Google Classroom, MS Teams, YouTube, Meet, G Suite, Google Search, Office 365, Canvas and NEO LMS\"','7 days','99 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Study 299','Smart','\"4GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Google Classroom, MS Teams, YouTube, Meet, G Suite, Google Search, Office 365, Canvas and NEO LMS\"','30 days','299 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Study 399','Smart','\"6GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Google Classroom, MS Teams, YouTube, Meet, G Suite, Google Search, Office 365, Canvas and NEO LMS\"','30 days','399 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Study 499','Smart','\"8GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Google Classroom, MS Teams, YouTube, Meet, G Suite, Google Search, Office 365, Canvas and NEO LMS\"','30 days','499 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Work 50','Smart','\"1GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove\"','3 days','50 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Work 99','Smart','\"2GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove\"','7 days','99 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Work 299','Smart','\"4GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove\"','30 days','299 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Work 399','Smart','\"6GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove\"','30 days','399 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Work 499','Smart','\"8GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove\"','30 days','499 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Work+ ALLNET 100','Smart','\"1GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls and texts to all networks\"','3 days','100 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Work+ ALLNET 199','Smart','\"2GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls and texts to all networks\"','7 days','199 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Work+ ALLNET 549','Smart','\"4GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls and texts to all networks\"','30 days','549 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Work+ ALLNET 649','Smart','\"6GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls and texts to all networks\"','30 days','649 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Work+ ALLNET 749','Smart','\"8GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day on Microsoft 365, MS Teams, Meet, WhatsApp, Grab, GrabPay, G Suite, Paymaya, Lazada, Shopee, Lalamove');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls and texts to all networks\"','30 days','749 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA K-VIDEO 50','Smart','\"1GB mobile data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB everyday for YouTube and Viu');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Free Viu Premium\"','7 days','199 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA PRO VIDEO 199','Smart','\"6GB mobile data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 3GB everyday for YouTube, NBA and More (Total of 21 GB)\"','7 days','199 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA PRO VIDEO 599','Smart','\"12GB mobile data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 3GB everyday for YouTube, NBA and More (Total of 45 GB)\"','15 days','599 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA PRO VIDEO 999','Smart','\"24GB mobile data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 3GB everyday for YouTube, NBA and More (Total of 90 GB)\"','30 days',' 999 Pesos');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SULITXT5','TM','25 Texts to TM/Globe','1 day','5');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('TXT10','TM','Unlimited texts to TM/Globe',' 2 days','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UNLIALLNET10','TM','Unlimited texts to all networks','1 day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('ASTIGTXT30','TM','Unlimited texts to TM/Globe',' 5 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UNLITAWAG15','TM','Unlimited calls to TM/Globe','1 day','15');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('TXT5 ','TM','Add-on to UNLITAWAG15 that extends the promo validity for another 1 day','1 day','5');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('DAGDAGTXT(add-on)','TM','Add-on to UNLITAWAG15 for an additional 100 Texts to all networks','1 day','5');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EXTEND5(add-on)','TM','Add-on that extends all unlimited call and text promos for another 1 day up to 365 days','1 day','5');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('COMBOALL10','TM','\"Unlimited calls to TM/Globe');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to TM/Globe');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 texts to all networks\"','1 day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('COMBOALL20','TM','\"Unlimited calls to TM/Globe');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to TM/Globe');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 texts to all networks\"','3 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('COMBO15','TM','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 120 minutes calls to TM/Globe\"','2 days','15');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('COMBO20','TM','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 120 minutes calls to TM/Globe\"','3 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('ML10','TM','1GB for Mobile Legends','3 days','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('FB10','TM','1GB for Facebook','3 days','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('FB15','TM','200MB for Facebook','2 days','15');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('FB30','TM','\"300MB for Facebook');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+Unlimited texts to all networks\"',' 3 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('FB50','TM','\"500MB for Facebook');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+Unlimited texts to all networks\"',' 5 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('FACEBOOK50','TM','600MB for Facebook','7 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('FB199','TM','1GB for Facebook','30 days','199');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF10','TM','40MB data','1 day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF15','TM','\"100MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 30MB for Instagram\"','2 days','15');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF30','TM','\"300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50MB for Facebook, Viber or Snapchat\"','2 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF50','TM','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB everyday for App of Choice (Facebook, YouTube, Mobile Legends, TikTok, etc.)');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF 70','TM','\"1GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB for App of Bundle (Facebook, YouTube, Mobile Legends, TikTok, etc.) per day for 7 days (7GB total).');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','7 days','70');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF 90','TM','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB everyday for App of Bundle (7GB total)');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','7 days','90');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF299','TM','\"2GB mobile data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10GB for App Bundle\"','30 days','299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF599','TM','\"5GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10GB for App Bundle\"','30 days','599');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF999','TM','\"10GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10GB for App Bundle\"','30 days','999');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF1299','TM','\"15GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10GB for App Bundle\"','30 days','1299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF1999','TM','\"30GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10GB for App Bundle\"','30 days','1999');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('EASYSURF2499','TM','\"50GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10GB for App Bundle\"','30 days','2499');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GG30','TM','\"300MB for Games');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"',' 3 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GG50','TM','\"500MB for Games');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','5 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GAMES15','TM','100MB game apps data',' 1 day','15');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GAMES20','TM','100MB for Games','2 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GAMES50','TM','300MB for Games','7 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GAMES99','TM','300MB for Games','30 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('FS FBIG','TM','400MB for Facebook and Instagram',' No Expiry','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('FS YTML','TM','400MB for YouTube and Mobile Legends','No Expiry','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('FS TikWS','TM','400MB for TikTok and WeSing','No Expiry','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('FS iWCOD','TM','400MB for iWant and Call of Duty','No Expiry','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('A20TY/AS20Y','TM','\"Unlimited calls to TM/Globe');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB YouTube data\"','2 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('A20FB/AS20FB','TM','\"Unlimited calls to TM/Globe');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB Facebook data\"','2 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('A20ML/AS20ML','TM','\"Unlimited calls to TM/Globe');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB Mobile Legends data\"','2 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('A20WP/AS20WP','TM','\"Unlimited calls to TM/Globe');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB Wattpad data\"','2 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SUPERSURF50','TM','Unlimited mobile internet','1 day','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SUPERSURF200','TM','Unlimited mobile internet','5 days','200');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('All-In Surf 30','TM','\"300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+700MB for Facebook, YouTube, TikTok, WeSing, iWant and Mobile Legends\"','3 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Winner Text 10','Sun','\"Unlimited texts to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10 minutes calls to Sun, Smart, and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access\"','1 Day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('TRINET 20','Sun','\"Unlimited texts to Sun, Smart and TNT');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 texts to other networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 60 minutes calls to Sun, Smart and TNT');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 30MB Facebook per day\"','3 Days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call Unlimited 30','Sun','\"Unlimited calls to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Chat\"','2 Days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Text All 30','Sun','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Chat\"','3 Days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call and Text Combo 10','Sun','\"10 minutes calls to Sun, Smart, and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 texts to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 texts to other networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access\"','1 Day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call and Text Combo 20','Sun','\"25 minutes calls to Sun, Smart, and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100 texts to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100 texts to other networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access\"','3 Days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call and Text Combo 30','Sun','\"40 minutes calls to Sun, Smart, and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 150 texts to Sun Cellular');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 150 texts to other networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Chat\"',' 3 Days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call and Text Combo 50','Sun','\"70 minutes calls to Sun, Smart, and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 250 texts to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 250 texts to other networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Chat\"','5 Days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Text Unlimited 20','Sun','\"Unlimited texts to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 texts to other networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 20 minutes calls Sun, Smart, and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access\"','3 Days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Text Unlimited 50','Sun','\"Unlimited texts to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 60 minutes calls to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Cha\"','10 Days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Text Unlimited 60','Sun','\"Unlimited texts to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 60 minutes calls to Sun, Smart, and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200 texts to other networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Chat\"','10 Days','60');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Text Unlimited 150','Sun','\"Unlimited texts to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 5 hours calls to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Chat');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Spinnr access\"','30 Days','150');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Text Unlimited 200','Sun','\" Unlimited texts to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 5 Hours calls to PLDT, Sun, Smart, Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1,000 texts to other networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Chat\"','30 Days','200');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Text Unlimited 300','Sun','\"Unlimited texts to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 10 hours calls to Sun, Smart, and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 3,000 texts to other networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Spinnr access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Chat\"','30 Days','300');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Non-Stop Surf 25','Sun','\"Non-stop Mobile Internet Surfing');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 25MB Internet Data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 300MB Spinnr Access and Streaming\"','1 Day','25');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Non-Stop Surf 50','Sun','\"Non-stop Mobile Internet Surfing');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB Internet Data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 500MB Spinnr Access and Streaming\"','3 Days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Non-Stop Surf 100','Sun','\"Non-stop Mobile Internet Surfing');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 250MB Internet Data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB Spinnr Access and Streaming\"',' 5 Days','100');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Non-Stop Surf 299','Sun','\"Non-stop Mobile Internet Surfing');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB Spinnr\"','30 Days','299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Non-Stop Surf 450','Sun','\"Non-stop Mobile Internet Surfing');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB Internet Data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB Spinnr\"','30 Days','450');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Non-Stop Surf 699','Sun','\"Non-stop Mobile Internet Surfing');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 2.5GB Internet Data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB Spinnr\"','30 Days','699');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call and Text Unlimited 25','Sun','\"Unlimited calls to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access\"','1 Day','25');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call and Text Unlimited 30','Sun','\"Unlimited calls to Sun, Smart and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Chat\"','1 Day','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call and Text Unlimited 50','Sun','\" Unlimited calls to Sun, Smart and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Facebook access');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Non-Stop Chat\"','3 Days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call and Text Unlimited 100','Sun','\" Unlimited calls to Sun, Smart and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB internet data\"','7 Days','100');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call and Text Unlimited 150','Sun','\"Unlimited calls to Sun, Smart and TNT');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 500MB data\"',' 7 Days','150');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Call and Text Unlimited 450','Sun','\" Unlimited calls Sun, Smart, and Talk ‘N Text');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1.5GB data\"','30 Days','450');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Wais 100','Sun','\"Unlimited calls to Sun Cellular');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to Sun Cellular\"','15 Days','100');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Wais 200','Sun','\"Unlimited calls to Sun Cellular');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to Sun Cellular');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 500 texts to Smart and TNT\"','30 Days','200');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('MB5','Sun','10MB data','1 Day','5');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('MB50','Sun','\"100MB Internet Data Allocation');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 500MB Spinnr\"','3 Days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('MB99','Sun','\"200MB Internet Data Allocation');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB Spinnr\"','30 Days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('MB250','Sun','\"700MB Internet Data Allocation');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB Spinnr\"','30 Days','250');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Photo Bundle 10','Sun','Access to Instagram, Flicker, Pinterest and Tumblr','1 Day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Photo Bundle 199','Sun','Access to Instagram, Flicker, Pinterest and Tumblr','30 Days','199');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Social Bundle 10','Sun','Access to Facebook, Twitter, Google Plus, Waze, Foursquare, Linkedln and Path','1 Day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Social Bundle 199','Sun','Access to Facebook, Twitter, Google Plus, Waze, Foursquare, Linkedln and Path','30 Days','199');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Email Bundle 10','Sun','Access to Gmail, Yahoo Mail, Outlook and Exchange','1 Day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Chat Bundle 10','Sun','Access to Facebook Messenger, Chikka Messenger, Line, WeChat, WhatsApp, Viber, Kakao and Oist',' 1 Day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Email Bundle 199','Sun','Access to Gmail, Yahoo Mail, Outlook and Exchange','30 Days','199');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Chat Bundle 249','Sun','Access to Facebook Messenger, Chikka Messenger, Line, WeChat, WhatsApp, Viber, Kakao and Oist','30 Days','249');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGASURF50','Sun','\"1GB open access data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 300MB YouTube');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','3 Days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Big Time Data 70','Sun','\"1GB internet data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 30 minutes calls to Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','7 Days','70');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB 20','TNT','\"100MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday of Facebook and Messenger');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','2 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB 30','TNT','\" 300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Facebook and Messenger');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ (BONUS) Unlimited calls to all networks\"','3 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB 99','TNT','\"1.5GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Facebook and Messenger');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ (BONUS) Unlimited calls to all networks\"','7 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB 199','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB everyday for Facebook and Messenger');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ (BONUS) Unlimited calls to all networks\"','30 days','199');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ML 20','TNT','\" 100MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','2 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ML 30','TNT','\"300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','3 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ML 99','TNT','\"1.5GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','7 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ML 199','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB everyday for Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','30 days','199');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ALLNET 40','TNT','\"100MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Facebook and Messenger');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun/Globe/TM\"',' 2 days','40');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ALLNET 55','TNT','\" 300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Facebook and Messenger');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun/Globe/TM\"','3 days','55');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ALLNET 149','TNT','\"1.5GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Facebook and Messenger');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun/Globe/TM\"','7 days','149');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ALLNET 319','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB everyday for Facebook and Messenger');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun/Globe/TM\"','30 days','319');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ALL-IN 45','TNT','\" 100MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Facebook, Instagram and Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun/Globe/TM\"','2 days','45');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ALL-IN 60','TNT','\"300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Facebook, Instagram and Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun/Globe/TM\"','3 days','60');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ALL-IN 159','TNT','\"1.5GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday for Facebook, Instagram and Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun/Globe/TM\"','7 days','159');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA ALL-IN 349','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB everyday for Facebook, Instagram and Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun/Globe/TM\"','30 days','349');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB+ML 30','TNT','\"100MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday you can consume for Facebook and/or Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','2 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB+ML 45','TNT','\"300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday you can consume for Facebook and/or Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','3 days','45');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB+ML 129','TNT','\"1.5GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday you can consume for Facebook and/or Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','7 days','129');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB+ML 259','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB everyday you can consume for Facebook and/or Mobile Legends');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','30 days','259');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB+IG 35','TNT','\"100MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday you can consume for Facebook and/or Instagram');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','2 days','35');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB+IG 50','TNT','\"300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday you can consume for Facebook and/or Instagram');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"',' 3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB+IG 139','TNT','\"1.5GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB everyday you can consume for Facebook and/or Instagram');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','7 days','139');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('SURFSAYA FB+IG 289','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB everyday you can consume for Facebook and/or Instagram');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/SMART/Sun\"','30 days','289');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA VIDEO 50','TNT','\"1GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA VIDEO 99','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play\"','7 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA VIDEO 299','TNT','\" 4GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play\"','30 days','299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA VIDEO 399','TNT','\"6GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play\"','30 days','399');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA VIDEO 499','TNT','\" 8GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play\"','30 days','499');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA VIDEO+ 75','TNT','\" 1GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart/TNT/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','3 days','75');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA VIDEO+ 149','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart/TNT/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"',' 7 days');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('','149');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA VIDEO+ 449','TNT','\"4GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart/TNT/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','30 days','449');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA VIDEO+ 549','TNT','\"6GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart/TNT/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','30 days','549');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA VIDEO+ 649','TNT','\"8GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for YouTube, NBA, iWant, iflix and Cignal Play');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to Smart/TNT/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','30 days','649');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA GAMES 50','TNT','\"1GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume to play Mobile Legends, FB Gaming, Clash of Clans, Arena of Valor and Clash Royale\"','3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA GAMES 99','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume to play Mobile Legends, FB Gaming, Clash of Clans, Arena of Valor and Clash Royale\"','7 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA GAMES 299','TNT','\"4GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume to play Mobile Legends, FB Gaming, Clash of Clans, Arena of Valor and Clash Royale\"','30 days','299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA GAMES 399','TNT','\"6GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume to play Mobile Legends, FB Gaming, Clash of Clans, Arena of Valor and Clash Royale\"','30 days','399');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA GAMES 499','TNT','\"8GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume to play Mobile Legends, FB Gaming, Clash of Clans, Arena of Valor and Clash Royale\"','30 days','499');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA STORIES 50','TNT','\"1GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for TikTok, Facebook, Instagram and Twitter\"','3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA STORIES 99','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for TikTok, Facebook, Instagram and Twitter\"','7 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA STORIES 299','TNT','\"4GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for TikTok, Facebook, Instagram and Twitter\"','30 days','299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA STORIES 399','TNT','\"6GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for TikTok, Facebook, Instagram and Twitter\"','30 days','399');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA STORIES 499','TNT','\"8GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day you can consume for TikTok, Facebook, Instagram and Twitter\"',' 30 days','499');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA STUDY 99','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day for Google Classroom, Google Meet, G Suite, Google Search, MS Teams, YouTube\"','','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA STUDY 299','TNT','\"4GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day for Google Classroom, Google Meet, G Suite, Google Search, MS Teams, YouTube\"','30 days','299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA WORK 50','TNT','\"1GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day for Grab, Lazada, Shopee, Paymaya, and more.\"','3 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA WORK 99','TNT','\"2GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day for Grab, Lazada, Shopee, Paymaya, and more.\"','7 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('GIGA WORK 299','TNT','\"4GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 1GB per day for Grab, Lazada, Shopee, Paymaya, and more.\"','30 days','299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Gaan Surf 5','TNT','15MB data','1 day','5');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Gaan Surf 10','TNT','\"50MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB for Facebook, YouTube and Mobile Legends\"','1 day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Gaan Text 10','TNT','Unlimited texts to all networks','1 day','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Clash of Clans 10','TNT','Access to Clash of Clans','3 days','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Facebook 10','TNT','Access to Facebook','3 days','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Mobile Legends 10','TNT','Access to Mobile Legends','3 days','10');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Alden & Maine Load 15','TNT','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 60 minutes calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB Facebook, Twitter, Viber, Clash of Clans and Dubsmash\"','1 day','15');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Gaan Surf 15','TNT','\"100MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB for Facebook, YouTube and Mobile Legends\"','2 days','15');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Gaan Text 20','TNT','Unlimited texts to all networks','2 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Super Combo 20','TNT','\"Unlimited calls and unlimited texts to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50MB data\"','2 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Unli Talk and Text 20','TNT','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB of Tropa Apps\"','1 day','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Unli Text 20','TNT','\"Unlimited texts to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 20 minutes calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 50 texts to other networks\"','3 days','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('All Day 20','TNT','800MB data but downloading and video streaming is unavailable','1 day','20');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Unlitext2All Plus 25','TNT','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 60 minutes calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB Facebook, Twitter, Viber, Clash of Clans and Dubsmash\"','3 days','25');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Unli All-Net Text 30','TNT','Unlimited texts to all networks','5 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('All Day 30','TNT','500MB access to all sites except video streaming and downloading','2 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Gaan Surf 30','TNT','\"300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB for Facebook, YouTube and Mobile Legends\"','5 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Panalo Data 30','TNT','\"500MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB for Facebook per day\"','2 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Panalo Combo 30','TNT','\"200MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 60 minutes calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','3 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('All Out Surf 30','TNT','\"300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 30 minutes calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','2 days','30');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Panalo 40','TNT','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('(Available only in North and Central Luzon, Visayas, and Mindanao provinces)\"','7 days','40');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Unlitext2All Plus 50','TNT','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 150 minutes calls to TNT/Smart/Sun\"','5 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Gaan Surf 50','TNT','\"500MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 200MB for Facebook, YouTube and Mobile Legends\"','7 days','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Giga Surf 50','TNT','\"1GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 300MB YouTube');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','1 day','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Surf Max 50','TNT','800MB data','1 day','50');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Unli All-Net Text 60','TNT','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 150 minutes calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 150MB of Tropa Apps\"','7 days','60');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Panalo Data 60','TNT','\"1GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','5 days','60');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Panalo Combo 60','TNT','\"500MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100 minutes calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to all networks\"','7 days','60');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Super Combo 70','TNT','\"300MB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited texts to TNT/Smart/Sun\"','5 days');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('','70');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Clash of Clans 99','TNT','1.5GB for Clash of Clans','30 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Facebook 99','TNT','1.5GB for Facebook','30 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('YouTube 99','TNT','1.5GB for YouTube','30 days','99');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Unli Talk and Text 100','TNT','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ Unlimited calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB Tropa Apps\"','7 days','100');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UTP150','TNT','\"Unlimited texts to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 150 minutes calls to TNT/Smart/Sun');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 150 texts to other networks\"','30 days','150');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('TROPA 150','TNT','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 60 minutes calls to TNT/Smart per day');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 100MB for Facebook, Twitter, COC, Dubsmash and Viber per day\"','15 days','150');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Gaan Surf 150','TNT','\"1.5GB data');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 750MB for Facebook, YouTube and Mobile Legends\"','30 days','150');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Surf Max 299','TNT','800MB data per day','7 days','299');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('UA300','TNT','\"Unlimited texts to all networks');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('+ 300 minutes calls to TNT/Smart/Sun\"','30 days','300');
INSERT INTO promo (promo,sim_prov,sim_desc,validity,cost) VALUES ('Surf Max 999','TNT','800MB data per day','30 days','999');
";


if ($conn->multi_query($sql) === TRUE) {
  echo "New records created successfully";
} else {
  echo "Error: " . $sql . "<br>" . $conn->error;
}

$conn->close();
?>
